### ISSUE TITLE
Does not compile with Rust 1.47.0

### ISSUE THREAD

**Issue by jan-auer** [luser/rust-minidump#100]
```
error[E0277]: the trait bound `[u16; 260]: scroll::ctx::TryFromCtx<'_, _>` is not satisfied
    --> minidump-common/src/format.rs:1322:25
     |
1322 |           #[derive(Clone, Pread, SizeWith)]
     |                           ^^^^^ the trait `scroll::ctx::TryFromCtx<'_, _>` is not implemented for `[u16; 260]`
...
1331 | / multi_structs! {
1332 | |     /// Miscellaneous process information
1333 | |     ///
1334 | |     /// This struct matches the [Microsoft struct][msdn] of the same name.
...    |
1376 | |     }
1377 | | }
     | |_- in this macro invocation
     |
     = help: the following implementations were found:
               <&'a [u8] as scroll::ctx::TryFromCtx<'a, usize>>
     = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
